services:
  backend:
    build: ./services/backend
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gameoflife
    volumes:
      - './services/backend:/app'
    command: npm run start
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    depends_on:
      - backend


  db:
    image: mongo:latest
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=gameoflife
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: